name: Build and deploy to Chrisalaxelrto
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3            
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew --no-daemon build

      - name: Upload jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-ukulele
          path: ukulele.jar

  deployment:
      needs: build
      runs-on: ubuntu-latest
      environment: Chrisalaxelrto
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: ${{ github.sha }}-ukulele
        - name: Stopping ukulele on server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: sudo systemctl stop ukulele

        - name: Copy jar file
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            source: "ukulele.jar"
            target: ${{ secrets.DIRECTORY }}

        - name: Restarting ukulele on server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: sudo systemctl start ukulele