name: Deploy to Chrisalaxelrto
on: [deployment]

jobs:
  deployment:
      runs-on: ubuntu-latest
      environment: Chrisalaxelrto
      steps:
        - name: Download latest release
          uses: dsaltares/fetch-gh-release-asset@master
          with:
            file: 'ukulele.jar'
        - name: Stopping ukulele on server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: sudo systemctl stop ukulele

        - name: Copy jar file
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            source: "ukulele.jar"
            target: ${{ secrets.DIRECTORY }}

        - name: Restarting ukulele on server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: sudo systemctl start ukulele