name: Deploy to VM
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3            
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: built-ukulele-jar
          path: ukulele/ukulele.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: built-ukulele-jar
      - name: Stopping ukulele on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: sudo systemctl stop ukulele

      - name: Copy jar file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "ukulele.jar"
          target: "/home/ajahueym/Documents/Gits/ukulele/"

      - name: Restarting ukulele on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: sudo systemctl start ukulele
